FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_DATABASE=userlogin
ENV MYSQL_ROOT_PASSWORD=password123
ENV MYSQL_USER=taha
ENV MYSQL_PASSWORD=password123

# Copy custom MySQL configuration file into the container
# This my.cnf file customisation makes the database open to external connection from port 3308
COPY my.cnf /etc/mysql/my.cnf

# Copy database schema and initialization scripts
COPY init.sql /docker-entrypoint-initdb.d/
COPY userlogin_comment.sql /docker-entrypoint-initdb.d/
COPY userlogin_genre.sql /docker-entrypoint-initdb.d/
COPY userlogin_language.sql /docker-entrypoint-initdb.d/
COPY userlogin_movie.sql /docker-entrypoint-initdb.d/
COPY userlogin_moviegenre.sql /docker-entrypoint-initdb.d/
COPY userlogin_movielanguage.sql /docker-entrypoint-initdb.d/
COPY userlogin_user.sql /docker-entrypoint-initdb.d/

# Expose the MySQL port
EXPOSE 3308
