FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_DATABASE=userlogin
ENV MYSQL_ROOT_PASSWORD=password123
ENV MYSQL_USER=taha
ENV MYSQL_PASSWORD=password123

# Copy database schema and initialization scripts
COPY init.sql /docker-entrypoint-initdb.d/

# Expose the MySQL port
EXPOSE 3306
